post http://127.0.0.1:3000/
Content-Type: multipart/form-data
Transfer-Encoding:chunked
X-Content-Type-Options:nosniff
Authorization: Basic 123:123
###

POST http://127.0.0.1:3000/chat http/1.1  
Content-Type:application/x-www-form-urlencoded
# Transfer-Encoding:chunked
Authorization: Basic 123:123

query=hung

###

get http://127.0.0.1:3000/train
Authorization: Basic 123:123


